import { defineCollection, reference } from 'astro:content';
import { z } from 'astro:schema';
import { glob, file } from 'astro/loaders';
import yaml from 'js-yaml';

/** Parse a YAML file into the array-of-objects shape the file() loader expects. */
const yamlParser = (text: string) => yaml.load(text) as Record<string, unknown>[];

/**
 * Blog posts and updates. One folder per post so images live beside the text:
 *   src/content/updates/2026-08-14-some-slug/index.md
 *   src/content/updates/2026-08-14-some-slug/chart.png
 */
const updates = defineCollection({
  loader: glob({ pattern: '**/index.md', base: './src/content/updates' }),
  schema: ({ image }) =>
    z.object({
      title: z.string(),
      // Doubles as the index entry and the social preview. Worth rewriting until good.
      standfirst: z.string(),
      date: z.coerce.date(),
      // `type` drives layout; `tags` describe subject. If in doubt it is a field note.
      type: z.enum(['field-note', 'deep-dive', 'paper-note']).default('field-note'),
      tags: z.array(z.string()).default([]),
      draft: z.boolean().default(false),
      // A post can become part of a series retroactively by adding this.
      series: z
        .object({
          name: z.string(),
          part: z.number().int().positive(),
        })
        .optional(),
      // Set when the piece is also published on research.infobip.com. Their URL
      // gets the search ranking, this site gets the reader.
      canonical: z.string().url().optional(),
      cover: image().optional(),
      // Optional link to the paper this post discusses.
      paper: reference('publications').optional(),
    }),
});

/**
 * Plain-language summaries of papers, generated by scripts/summarize_papers.py.
 * Metadata (title, venue, links) comes from the publication entry, not here.
 */
const paperNotes = defineCollection({
  loader: glob({ pattern: '*.md', base: './src/content/paper-notes' }),
  schema: z.object({
    paper: reference('publications'),
    generated: z.coerce.date().optional(),
  }),
});

const venueKind = z.enum([
  'conference',
  'journal',
  'workshop',
  'book-chapter',
  'demo',
  'thesis',
  'newsletter',
  'industry',
  'preprint',
]);

/**
 * The publication record. Single source of truth: the page, the BibTeX and the
 * APA string are all generated from these fields, so they cannot disagree.
 */
const publications = defineCollection({
  loader: file('src/data/publications.yml', { parser: yamlParser }),
  schema: z.object({
    title: z.string(),
    /** In publication order. Rendered with your own name emphasised. */
    authors: z.array(z.string()).min(1),
    year: z.number().int().min(2000).max(2100),
    venue: z.object({
      /** Short name as a peer would say it, e.g. "ECIR". */
      name: z.string(),
      /** Full name for the citation, e.g. "45th European Conference on Information Retrieval". */
      full: z.string().optional(),
      kind: venueKind,
      publisher: z.string().optional(),
      pages: z.string().optional(),
      volume: z.string().optional(),
      colocatedWith: z.string().optional(),
    }),
    pdf: z.string().optional(),
    poster: z.string().optional(),
    slides: z.string().optional(),
    doi: z.string().optional(),
    url: z.string().url().optional(),
    /** Shown in "Selected work" on the landing page. */
    selected: z.boolean().default(false),
    /** Ordering within the selected list; lower comes first. */
    selectedRank: z.number().int().positive().optional(),
    /** Research topics for filtering on /publications. Open vocabulary. */
    areas: z.array(z.string()).default([]),
    /**
     * Team AIR / Infobip research outcome. Separate from topic `areas`.
     * Used by the publications Team AIR filter and (later) the AIR page.
     */
    air: z.boolean().default(false),
    /**
     * Set by scripts/add_paper.py when metadata was machine-extracted.
     * The build warns until it is cleared. Never ship a true value.
     */
    needsReview: z.boolean().default(false),
  }),
});

const talks = defineCollection({
  loader: file('src/data/talks.yml', { parser: yamlParser }),
  schema: z.object({
    title: z.string(),
    event: z.string(),
    location: z.string().optional(),
    date: z.coerce.date(),
    kind: z.enum(['keynote', 'talk', 'panel', 'tutorial', 'invited', 'chair']).default('talk'),
    slides: z.string().optional(),
    video: z.string().url().optional(),
    url: z.string().url().optional(),
    description: z.string().optional(),
  }),
});

const service = defineCollection({
  loader: file('src/data/service.yml', { parser: yamlParser }),
  schema: z.object({
    category: z.enum([
      'programme-committee',
      'reviewing',
      'organising',
      'editorial',
      'chairing',
      'supervision',
    ]),
    role: z.string(),
    venue: z.string().optional(),
    years: z.string().optional(),
    detail: z.string().optional(),
    url: z.string().url().optional(),
  }),
});

export const collections = { updates, paperNotes, publications, talks, service };
